# Stage 1: Install dependencies
FROM node:22-alpine AS installer

WORKDIR /usr/src/app
RUN npm i pnpm -g
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --ignore-scripts
COPY . .
RUN pnpm postinstall

# Stage 2: Development server
FROM node:22-alpine AS dev

WORKDIR /usr/src/app
RUN npm i pnpm -g
COPY --from=installer /usr/src/app/ ./
CMD [ "pnpm", "dev:docker" ]